/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;


import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {

    public static void main(String[] args)
    {
        BufferedImage img = null;
        File f = null;

        //read image
        try{
            f = new File("src/main/resources/test.jpg");
            img = ImageIO.read(f);
        }catch (IOException e){
            System.out.println(e);
        }

        Bitmap bmp = new Bitmap(img);
//      BufferedImage bf = bmp.grayscale(img);
//      BufferedImage bf = bmp.resize(img);
        BufferedImage bf = bmp.blur(img);
      try{
          f = new File("src/main/resources/Output3.jpg");
          System.out.println("writing to output file");
          ImageIO.write(bf,"jpg",f);
      }
      catch (IOException e){
          System.out.println(e);
      }


    }
}
